// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pm/v1/issue.proto

package pmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // "PMV-42"
	TypeId        int64                  `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                            // workflow state name
	Priority      string                 `protobuf:"bytes,8,opt,name=priority,proto3" json:"priority,omitempty"`                        // "highest".."lowest"
	AssigneeId    int64                  `protobuf:"varint,9,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"` // 0 if unassigned
	ReporterId    int64                  `protobuf:"varint,10,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,11,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 0 if not a subtask
	SprintId      int64                  `protobuf:"varint,12,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"` // 0 if backlog
	StoryPoints   int32                  `protobuf:"varint,13,opt,name=story_points,json=storyPoints,proto3" json:"story_points,omitempty"`
	Labels        []string               `protobuf:"bytes,14,rep,name=labels,proto3" json:"labels,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_pm_v1_issue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{0}
}

func (x *Issue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Issue) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Issue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Issue) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Issue) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Issue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Issue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Issue) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Issue) GetAssigneeId() int64 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

func (x *Issue) GetReporterId() int64 {
	if x != nil {
		return x.ReporterId
	}
	return 0
}

func (x *Issue) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Issue) GetSprintId() int64 {
	if x != nil {
		return x.SprintId
	}
	return 0
}

func (x *Issue) GetStoryPoints() int32 {
	if x != nil {
		return x.StoryPoints
	}
	return 0
}

func (x *Issue) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Issue) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Issue) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Issue) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Sprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // "planned" | "active" | "completed"
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sprint) Reset() {
	*x = Sprint{}
	mi := &file_pm_v1_issue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sprint) ProtoMessage() {}

func (x *Sprint) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sprint.ProtoReflect.Descriptor instead.
func (*Sprint) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{1}
}

func (x *Sprint) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sprint) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Sprint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sprint) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Sprint) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Sprint) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Sprint) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // "PMV-42"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueRequest) Reset() {
	*x = GetIssueRequest{}
	mi := &file_pm_v1_issue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueRequest) ProtoMessage() {}

func (x *GetIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueRequest.ProtoReflect.Descriptor instead.
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{2}
}

func (x *GetIssueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueResponse) Reset() {
	*x = GetIssueResponse{}
	mi := &file_pm_v1_issue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueResponse) ProtoMessage() {}

func (x *GetIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueResponse.ProtoReflect.Descriptor instead.
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{3}
}

func (x *GetIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type ListIssuesByProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                      // optional filter
	SprintId      int64                  `protobuf:"varint,3,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"` // optional filter (0 = ignore)
	Page          *PageRequest           `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesByProjectRequest) Reset() {
	*x = ListIssuesByProjectRequest{}
	mi := &file_pm_v1_issue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesByProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesByProjectRequest) ProtoMessage() {}

func (x *ListIssuesByProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesByProjectRequest.ProtoReflect.Descriptor instead.
func (*ListIssuesByProjectRequest) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{4}
}

func (x *ListIssuesByProjectRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListIssuesByProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListIssuesByProjectRequest) GetSprintId() int64 {
	if x != nil {
		return x.SprintId
	}
	return 0
}

func (x *ListIssuesByProjectRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListIssuesByProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesByProjectResponse) Reset() {
	*x = ListIssuesByProjectResponse{}
	mi := &file_pm_v1_issue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesByProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesByProjectResponse) ProtoMessage() {}

func (x *ListIssuesByProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesByProjectResponse.ProtoReflect.Descriptor instead.
func (*ListIssuesByProjectResponse) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{5}
}

func (x *ListIssuesByProjectResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ListIssuesByProjectResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      int64                  `protobuf:"varint,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSprintRequest) Reset() {
	*x = GetSprintRequest{}
	mi := &file_pm_v1_issue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSprintRequest) ProtoMessage() {}

func (x *GetSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSprintRequest.ProtoReflect.Descriptor instead.
func (*GetSprintRequest) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{6}
}

func (x *GetSprintRequest) GetSprintId() int64 {
	if x != nil {
		return x.SprintId
	}
	return 0
}

type GetSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *Sprint                `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSprintResponse) Reset() {
	*x = GetSprintResponse{}
	mi := &file_pm_v1_issue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSprintResponse) ProtoMessage() {}

func (x *GetSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSprintResponse.ProtoReflect.Descriptor instead.
func (*GetSprintResponse) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{7}
}

func (x *GetSprintResponse) GetSprint() *Sprint {
	if x != nil {
		return x.Sprint
	}
	return nil
}

type IssueCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       int64                  `protobuf:"varint,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	ReporterId    int64                  `protobuf:"varint,5,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	AssigneeId    int64                  `protobuf:"varint,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCreatedEvent) Reset() {
	*x = IssueCreatedEvent{}
	mi := &file_pm_v1_issue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCreatedEvent) ProtoMessage() {}

func (x *IssueCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCreatedEvent.ProtoReflect.Descriptor instead.
func (*IssueCreatedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{8}
}

func (x *IssueCreatedEvent) GetIssueId() int64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *IssueCreatedEvent) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *IssueCreatedEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IssueCreatedEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *IssueCreatedEvent) GetReporterId() int64 {
	if x != nil {
		return x.ReporterId
	}
	return 0
}

func (x *IssueCreatedEvent) GetAssigneeId() int64 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

type IssueUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       int64                  `protobuf:"varint,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ChangedFields []string               `protobuf:"bytes,3,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueUpdatedEvent) Reset() {
	*x = IssueUpdatedEvent{}
	mi := &file_pm_v1_issue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueUpdatedEvent) ProtoMessage() {}

func (x *IssueUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueUpdatedEvent.ProtoReflect.Descriptor instead.
func (*IssueUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{9}
}

func (x *IssueUpdatedEvent) GetIssueId() int64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *IssueUpdatedEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IssueUpdatedEvent) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

type IssueTransitionedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       int64                  `protobuf:"varint,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	FromStatus    string                 `protobuf:"bytes,3,opt,name=from_status,json=fromStatus,proto3" json:"from_status,omitempty"`
	ToStatus      string                 `protobuf:"bytes,4,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTransitionedEvent) Reset() {
	*x = IssueTransitionedEvent{}
	mi := &file_pm_v1_issue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTransitionedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTransitionedEvent) ProtoMessage() {}

func (x *IssueTransitionedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTransitionedEvent.ProtoReflect.Descriptor instead.
func (*IssueTransitionedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{10}
}

func (x *IssueTransitionedEvent) GetIssueId() int64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *IssueTransitionedEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IssueTransitionedEvent) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *IssueTransitionedEvent) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

type CommentAddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	IssueId       int64                  `protobuf:"varint,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	IssueKey      string                 `protobuf:"bytes,3,opt,name=issue_key,json=issueKey,proto3" json:"issue_key,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Mentions      []int64                `protobuf:"varint,5,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentAddedEvent) Reset() {
	*x = CommentAddedEvent{}
	mi := &file_pm_v1_issue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentAddedEvent) ProtoMessage() {}

func (x *CommentAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentAddedEvent.ProtoReflect.Descriptor instead.
func (*CommentAddedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{11}
}

func (x *CommentAddedEvent) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentAddedEvent) GetIssueId() int64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *CommentAddedEvent) GetIssueKey() string {
	if x != nil {
		return x.IssueKey
	}
	return ""
}

func (x *CommentAddedEvent) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CommentAddedEvent) GetMentions() []int64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type IssueLinkedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIssueId   int64                  `protobuf:"varint,1,opt,name=from_issue_id,json=fromIssueId,proto3" json:"from_issue_id,omitempty"`
	ToIssueId     int64                  `protobuf:"varint,2,opt,name=to_issue_id,json=toIssueId,proto3" json:"to_issue_id,omitempty"`
	LinkType      string                 `protobuf:"bytes,3,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"` // "blocks" | "relates" | "duplicates"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueLinkedEvent) Reset() {
	*x = IssueLinkedEvent{}
	mi := &file_pm_v1_issue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueLinkedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLinkedEvent) ProtoMessage() {}

func (x *IssueLinkedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLinkedEvent.ProtoReflect.Descriptor instead.
func (*IssueLinkedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{12}
}

func (x *IssueLinkedEvent) GetFromIssueId() int64 {
	if x != nil {
		return x.FromIssueId
	}
	return 0
}

func (x *IssueLinkedEvent) GetToIssueId() int64 {
	if x != nil {
		return x.ToIssueId
	}
	return 0
}

func (x *IssueLinkedEvent) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

type SprintStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      int64                  `protobuf:"varint,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SprintStartedEvent) Reset() {
	*x = SprintStartedEvent{}
	mi := &file_pm_v1_issue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprintStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprintStartedEvent) ProtoMessage() {}

func (x *SprintStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprintStartedEvent.ProtoReflect.Descriptor instead.
func (*SprintStartedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{13}
}

func (x *SprintStartedEvent) GetSprintId() int64 {
	if x != nil {
		return x.SprintId
	}
	return 0
}

func (x *SprintStartedEvent) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SprintStartedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SprintCompletedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SprintId        int64                  `protobuf:"varint,1,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	ProjectId       int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CompletedPoints int32                  `protobuf:"varint,3,opt,name=completed_points,json=completedPoints,proto3" json:"completed_points,omitempty"`
	IncompleteCount int32                  `protobuf:"varint,4,opt,name=incomplete_count,json=incompleteCount,proto3" json:"incomplete_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SprintCompletedEvent) Reset() {
	*x = SprintCompletedEvent{}
	mi := &file_pm_v1_issue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprintCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprintCompletedEvent) ProtoMessage() {}

func (x *SprintCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_issue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprintCompletedEvent.ProtoReflect.Descriptor instead.
func (*SprintCompletedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_issue_proto_rawDescGZIP(), []int{14}
}

func (x *SprintCompletedEvent) GetSprintId() int64 {
	if x != nil {
		return x.SprintId
	}
	return 0
}

func (x *SprintCompletedEvent) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SprintCompletedEvent) GetCompletedPoints() int32 {
	if x != nil {
		return x.CompletedPoints
	}
	return 0
}

func (x *SprintCompletedEvent) GetIncompleteCount() int32 {
	if x != nil {
		return x.IncompleteCount
	}
	return 0
}

var File_pm_v1_issue_proto protoreflect.FileDescriptor

const file_pm_v1_issue_proto_rawDesc = "" +
	"\n" +
	"\x11pm/v1/issue.proto\x12\x05pm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12pm/v1/common.proto\"\xb5\x04\n" +
	"\x05Issue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x17\n" +
	"\atype_id\x18\x04 \x01(\x03R\x06typeId\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\b \x01(\tR\bpriority\x12\x1f\n" +
	"\vassignee_id\x18\t \x01(\x03R\n" +
	"assigneeId\x12\x1f\n" +
	"\vreporter_id\x18\n" +
	" \x01(\x03R\n" +
	"reporterId\x12\x1b\n" +
	"\tparent_id\x18\v \x01(\x03R\bparentId\x12\x1b\n" +
	"\tsprint_id\x18\f \x01(\x03R\bsprintId\x12!\n" +
	"\fstory_points\x18\r \x01(\x05R\vstoryPoints\x12\x16\n" +
	"\x06labels\x18\x0e \x03(\tR\x06labels\x125\n" +
	"\bdue_date\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe7\x01\n" +
	"\x06Sprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x129\n" +
	"\n" +
	"start_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"#\n" +
	"\x0fGetIssueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"6\n" +
	"\x10GetIssueResponse\x12\"\n" +
	"\x05issue\x18\x01 \x01(\v2\f.pm.v1.IssueR\x05issue\"\x98\x01\n" +
	"\x1aListIssuesByProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tsprint_id\x18\x03 \x01(\x03R\bsprintId\x12&\n" +
	"\x04page\x18\x04 \x01(\v2\x12.pm.v1.PageRequestR\x04page\"l\n" +
	"\x1bListIssuesByProjectResponse\x12$\n" +
	"\x06issues\x18\x01 \x03(\v2\f.pm.v1.IssueR\x06issues\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.pm.v1.PageResponseR\x04page\"/\n" +
	"\x10GetSprintRequest\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\x03R\bsprintId\":\n" +
	"\x11GetSprintResponse\x12%\n" +
	"\x06sprint\x18\x01 \x01(\v2\r.pm.v1.SprintR\x06sprint\"\xbb\x01\n" +
	"\x11IssueCreatedEvent\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\x03R\aissueId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1f\n" +
	"\vreporter_id\x18\x05 \x01(\x03R\n" +
	"reporterId\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\x03R\n" +
	"assigneeId\"g\n" +
	"\x11IssueUpdatedEvent\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\x03R\aissueId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12%\n" +
	"\x0echanged_fields\x18\x03 \x03(\tR\rchangedFields\"\x83\x01\n" +
	"\x16IssueTransitionedEvent\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\x03R\aissueId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1f\n" +
	"\vfrom_status\x18\x03 \x01(\tR\n" +
	"fromStatus\x12\x1b\n" +
	"\tto_status\x18\x04 \x01(\tR\btoStatus\"\xa3\x01\n" +
	"\x11CommentAddedEvent\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\x03R\aissueId\x12\x1b\n" +
	"\tissue_key\x18\x03 \x01(\tR\bissueKey\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x1a\n" +
	"\bmentions\x18\x05 \x03(\x03R\bmentions\"s\n" +
	"\x10IssueLinkedEvent\x12\"\n" +
	"\rfrom_issue_id\x18\x01 \x01(\x03R\vfromIssueId\x12\x1e\n" +
	"\vto_issue_id\x18\x02 \x01(\x03R\ttoIssueId\x12\x1b\n" +
	"\tlink_type\x18\x03 \x01(\tR\blinkType\"d\n" +
	"\x12SprintStartedEvent\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\x03R\bsprintId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xa8\x01\n" +
	"\x14SprintCompletedEvent\x12\x1b\n" +
	"\tsprint_id\x18\x01 \x01(\x03R\bsprintId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12)\n" +
	"\x10completed_points\x18\x03 \x01(\x05R\x0fcompletedPoints\x12)\n" +
	"\x10incomplete_count\x18\x04 \x01(\x05R\x0fincompleteCount2\xe9\x01\n" +
	"\fIssueService\x12;\n" +
	"\bGetIssue\x12\x16.pm.v1.GetIssueRequest\x1a\x17.pm.v1.GetIssueResponse\x12\\\n" +
	"\x13ListIssuesByProject\x12!.pm.v1.ListIssuesByProjectRequest\x1a\".pm.v1.ListIssuesByProjectResponse\x12>\n" +
	"\tGetSprint\x12\x17.pm.v1.GetSprintRequest\x1a\x18.pm.v1.GetSprintResponseBV\n" +
	"\x1acom.pmplatform.proto.pm.v1B\n" +
	"IssueProtoP\x01Z*github.com/pm-platform/proto-go/pm/v1;pmv1b\x06proto3"

var (
	file_pm_v1_issue_proto_rawDescOnce sync.Once
	file_pm_v1_issue_proto_rawDescData []byte
)

func file_pm_v1_issue_proto_rawDescGZIP() []byte {
	file_pm_v1_issue_proto_rawDescOnce.Do(func() {
		file_pm_v1_issue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pm_v1_issue_proto_rawDesc), len(file_pm_v1_issue_proto_rawDesc)))
	})
	return file_pm_v1_issue_proto_rawDescData
}

var file_pm_v1_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pm_v1_issue_proto_goTypes = []any{
	(*Issue)(nil),                       // 0: pm.v1.Issue
	(*Sprint)(nil),                      // 1: pm.v1.Sprint
	(*GetIssueRequest)(nil),             // 2: pm.v1.GetIssueRequest
	(*GetIssueResponse)(nil),            // 3: pm.v1.GetIssueResponse
	(*ListIssuesByProjectRequest)(nil),  // 4: pm.v1.ListIssuesByProjectRequest
	(*ListIssuesByProjectResponse)(nil), // 5: pm.v1.ListIssuesByProjectResponse
	(*GetSprintRequest)(nil),            // 6: pm.v1.GetSprintRequest
	(*GetSprintResponse)(nil),           // 7: pm.v1.GetSprintResponse
	(*IssueCreatedEvent)(nil),           // 8: pm.v1.IssueCreatedEvent
	(*IssueUpdatedEvent)(nil),           // 9: pm.v1.IssueUpdatedEvent
	(*IssueTransitionedEvent)(nil),      // 10: pm.v1.IssueTransitionedEvent
	(*CommentAddedEvent)(nil),           // 11: pm.v1.CommentAddedEvent
	(*IssueLinkedEvent)(nil),            // 12: pm.v1.IssueLinkedEvent
	(*SprintStartedEvent)(nil),          // 13: pm.v1.SprintStartedEvent
	(*SprintCompletedEvent)(nil),        // 14: pm.v1.SprintCompletedEvent
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
	(*PageRequest)(nil),                 // 16: pm.v1.PageRequest
	(*PageResponse)(nil),                // 17: pm.v1.PageResponse
}
var file_pm_v1_issue_proto_depIdxs = []int32{
	15, // 0: pm.v1.Issue.due_date:type_name -> google.protobuf.Timestamp
	15, // 1: pm.v1.Issue.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: pm.v1.Issue.updated_at:type_name -> google.protobuf.Timestamp
	15, // 3: pm.v1.Sprint.start_date:type_name -> google.protobuf.Timestamp
	15, // 4: pm.v1.Sprint.end_date:type_name -> google.protobuf.Timestamp
	0,  // 5: pm.v1.GetIssueResponse.issue:type_name -> pm.v1.Issue
	16, // 6: pm.v1.ListIssuesByProjectRequest.page:type_name -> pm.v1.PageRequest
	0,  // 7: pm.v1.ListIssuesByProjectResponse.issues:type_name -> pm.v1.Issue
	17, // 8: pm.v1.ListIssuesByProjectResponse.page:type_name -> pm.v1.PageResponse
	1,  // 9: pm.v1.GetSprintResponse.sprint:type_name -> pm.v1.Sprint
	2,  // 10: pm.v1.IssueService.GetIssue:input_type -> pm.v1.GetIssueRequest
	4,  // 11: pm.v1.IssueService.ListIssuesByProject:input_type -> pm.v1.ListIssuesByProjectRequest
	6,  // 12: pm.v1.IssueService.GetSprint:input_type -> pm.v1.GetSprintRequest
	3,  // 13: pm.v1.IssueService.GetIssue:output_type -> pm.v1.GetIssueResponse
	5,  // 14: pm.v1.IssueService.ListIssuesByProject:output_type -> pm.v1.ListIssuesByProjectResponse
	7,  // 15: pm.v1.IssueService.GetSprint:output_type -> pm.v1.GetSprintResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pm_v1_issue_proto_init() }
func file_pm_v1_issue_proto_init() {
	if File_pm_v1_issue_proto != nil {
		return
	}
	file_pm_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pm_v1_issue_proto_rawDesc), len(file_pm_v1_issue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pm_v1_issue_proto_goTypes,
		DependencyIndexes: file_pm_v1_issue_proto_depIdxs,
		MessageInfos:      file_pm_v1_issue_proto_msgTypes,
	}.Build()
	File_pm_v1_issue_proto = out.File
	file_pm_v1_issue_proto_goTypes = nil
	file_pm_v1_issue_proto_depIdxs = nil
}
