// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pm/v1/issue.proto

package pmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IssueService_GetIssue_FullMethodName            = "/pm.v1.IssueService/GetIssue"
	IssueService_ListIssuesByProject_FullMethodName = "/pm.v1.IssueService/ListIssuesByProject"
	IssueService_GetSprint_FullMethodName           = "/pm.v1.IssueService/GetSprint"
)

// IssueServiceClient is the client API for IssueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IssueService — internal gRPC API exposed by issue-service (Java/Spring).
//
// Other services (mcp-server, gateway gRPC path) call this to read issue and
// sprint data. Public REST endpoints (FE → api-gateway → issue-service) are
// NOT modeled here. search/report/notification get issue data by consuming
// the `issue.events` Kafka topic, NOT via this API.
type IssueServiceClient interface {
	GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error)
	ListIssuesByProject(ctx context.Context, in *ListIssuesByProjectRequest, opts ...grpc.CallOption) (*ListIssuesByProjectResponse, error)
	GetSprint(ctx context.Context, in *GetSprintRequest, opts ...grpc.CallOption) (*GetSprintResponse, error)
}

type issueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssueServiceClient(cc grpc.ClientConnInterface) IssueServiceClient {
	return &issueServiceClient{cc}
}

func (c *issueServiceClient) GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIssueResponse)
	err := c.cc.Invoke(ctx, IssueService_GetIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueServiceClient) ListIssuesByProject(ctx context.Context, in *ListIssuesByProjectRequest, opts ...grpc.CallOption) (*ListIssuesByProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssuesByProjectResponse)
	err := c.cc.Invoke(ctx, IssueService_ListIssuesByProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueServiceClient) GetSprint(ctx context.Context, in *GetSprintRequest, opts ...grpc.CallOption) (*GetSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSprintResponse)
	err := c.cc.Invoke(ctx, IssueService_GetSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssueServiceServer is the server API for IssueService service.
// All implementations should embed UnimplementedIssueServiceServer
// for forward compatibility.
//
// IssueService — internal gRPC API exposed by issue-service (Java/Spring).
//
// Other services (mcp-server, gateway gRPC path) call this to read issue and
// sprint data. Public REST endpoints (FE → api-gateway → issue-service) are
// NOT modeled here. search/report/notification get issue data by consuming
// the `issue.events` Kafka topic, NOT via this API.
type IssueServiceServer interface {
	GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error)
	ListIssuesByProject(context.Context, *ListIssuesByProjectRequest) (*ListIssuesByProjectResponse, error)
	GetSprint(context.Context, *GetSprintRequest) (*GetSprintResponse, error)
}

// UnimplementedIssueServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssueServiceServer struct{}

func (UnimplementedIssueServiceServer) GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIssue not implemented")
}
func (UnimplementedIssueServiceServer) ListIssuesByProject(context.Context, *ListIssuesByProjectRequest) (*ListIssuesByProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIssuesByProject not implemented")
}
func (UnimplementedIssueServiceServer) GetSprint(context.Context, *GetSprintRequest) (*GetSprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSprint not implemented")
}
func (UnimplementedIssueServiceServer) testEmbeddedByValue() {}

// UnsafeIssueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssueServiceServer will
// result in compilation errors.
type UnsafeIssueServiceServer interface {
	mustEmbedUnimplementedIssueServiceServer()
}

func RegisterIssueServiceServer(s grpc.ServiceRegistrar, srv IssueServiceServer) {
	// If the following call panics, it indicates UnimplementedIssueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IssueService_ServiceDesc, srv)
}

func _IssueService_GetIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).GetIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_GetIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).GetIssue(ctx, req.(*GetIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueService_ListIssuesByProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssuesByProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).ListIssuesByProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_ListIssuesByProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).ListIssuesByProject(ctx, req.(*ListIssuesByProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueService_GetSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).GetSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_GetSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).GetSprint(ctx, req.(*GetSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IssueService_ServiceDesc is the grpc.ServiceDesc for IssueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pm.v1.IssueService",
	HandlerType: (*IssueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIssue",
			Handler:    _IssueService_GetIssue_Handler,
		},
		{
			MethodName: "ListIssuesByProject",
			Handler:    _IssueService_ListIssuesByProject_Handler,
		},
		{
			MethodName: "GetSprint",
			Handler:    _IssueService_GetSprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pm/v1/issue.proto",
}
