// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pm/v1/workspace.proto

package pmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Plan          string                 `protobuf:"bytes,5,opt,name=plan,proto3" json:"plan,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_pm_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workspace) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Workspace) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *Workspace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   int64                  `protobuf:"varint,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LeadId        int64                  `protobuf:"varint,5,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_pm_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *Project) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetLeadId() int64 {
	if x != nil {
		return x.LeadId
	}
	return 0
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorkspaceId   int64                  `protobuf:"varint,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_pm_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Member) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *Member) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Member) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsSystem      bool                   `protobuf:"varint,3,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_pm_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_pm_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspaceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceResponse) Reset() {
	*x = GetWorkspaceResponse{}
	mi := &file_pm_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceResponse) ProtoMessage() {}

func (x *GetWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_pm_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkspacesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_pm_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type CheckMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMembershipRequest) Reset() {
	*x = CheckMembershipRequest{}
	mi := &file_pm_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMembershipRequest) ProtoMessage() {}

func (x *CheckMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMembershipRequest.ProtoReflect.Descriptor instead.
func (*CheckMembershipRequest) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *CheckMembershipRequest) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *CheckMembershipRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMembershipResponse) Reset() {
	*x = CheckMembershipResponse{}
	mi := &file_pm_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMembershipResponse) ProtoMessage() {}

func (x *CheckMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMembershipResponse.ProtoReflect.Descriptor instead.
func (*CheckMembershipResponse) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *CheckMembershipResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *CheckMembershipResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type WorkspaceCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceCreatedEvent) Reset() {
	*x = WorkspaceCreatedEvent{}
	mi := &file_pm_v1_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceCreatedEvent) ProtoMessage() {}

func (x *WorkspaceCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceCreatedEvent.ProtoReflect.Descriptor instead.
func (*WorkspaceCreatedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *WorkspaceCreatedEvent) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *WorkspaceCreatedEvent) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *WorkspaceCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceCreatedEvent) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type ProjectCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorkspaceId   int64                  `protobuf:"varint,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // project key, e.g. "PMV" — issues become PMV-1, PMV-2...
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LeadId        int64                  `protobuf:"varint,5,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"` // 0 if unset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreatedEvent) Reset() {
	*x = ProjectCreatedEvent{}
	mi := &file_pm_v1_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreatedEvent) ProtoMessage() {}

func (x *ProjectCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreatedEvent.ProtoReflect.Descriptor instead.
func (*ProjectCreatedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectCreatedEvent) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectCreatedEvent) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *ProjectCreatedEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProjectCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectCreatedEvent) GetLeadId() int64 {
	if x != nil {
		return x.LeadId
	}
	return 0
}

type MemberAddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // role name: "owner" | "member" | custom
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberAddedEvent) Reset() {
	*x = MemberAddedEvent{}
	mi := &file_pm_v1_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberAddedEvent) ProtoMessage() {}

func (x *MemberAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberAddedEvent.ProtoReflect.Descriptor instead.
func (*MemberAddedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{12}
}

func (x *MemberAddedEvent) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *MemberAddedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberAddedEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type MemberRemovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   int64                  `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRemovedEvent) Reset() {
	*x = MemberRemovedEvent{}
	mi := &file_pm_v1_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRemovedEvent) ProtoMessage() {}

func (x *MemberRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_v1_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRemovedEvent.ProtoReflect.Descriptor instead.
func (*MemberRemovedEvent) Descriptor() ([]byte, []int) {
	return file_pm_v1_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *MemberRemovedEvent) GetWorkspaceId() int64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *MemberRemovedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_pm_v1_workspace_proto protoreflect.FileDescriptor

const file_pm_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x15pm/v1/workspace.proto\x12\x05pm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x01\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04plan\x18\x05 \x01(\tR\x04plan\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\x03R\vworkspaceId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\alead_id\x18\x05 \x01(\x03R\x06leadId\"\x91\x01\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\x03R\vworkspaceId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"G\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_system\x18\x03 \x01(\bR\bisSystem\"%\n" +
	"\x13GetWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x14GetWorkspaceResponse\x12.\n" +
	"\tworkspace\x18\x01 \x01(\v2\x10.pm.v1.WorkspaceR\tworkspace\"0\n" +
	"\x15ListWorkspacesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"J\n" +
	"\x16ListWorkspacesResponse\x120\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x10.pm.v1.WorkspaceR\n" +
	"workspaces\"T\n" +
	"\x16CheckMembershipRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"J\n" +
	"\x17CheckMembershipResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"}\n" +
	"\x15WorkspaceCreatedEvent\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\"\x96\x01\n" +
	"\x13ProjectCreatedEvent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\x03R\vworkspaceId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\alead_id\x18\x05 \x01(\x03R\x06leadId\"b\n" +
	"\x10MemberAddedEvent\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"P\n" +
	"\x12MemberRemovedEvent\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x03R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId2\xfc\x01\n" +
	"\x10WorkspaceService\x12G\n" +
	"\fGetWorkspace\x12\x1a.pm.v1.GetWorkspaceRequest\x1a\x1b.pm.v1.GetWorkspaceResponse\x12M\n" +
	"\x0eListWorkspaces\x12\x1c.pm.v1.ListWorkspacesRequest\x1a\x1d.pm.v1.ListWorkspacesResponse\x12P\n" +
	"\x0fCheckMembership\x12\x1d.pm.v1.CheckMembershipRequest\x1a\x1e.pm.v1.CheckMembershipResponseBZ\n" +
	"\x1acom.pmplatform.proto.pm.v1B\x0eWorkspaceProtoP\x01Z*github.com/pm-platform/proto-go/pm/v1;pmv1b\x06proto3"

var (
	file_pm_v1_workspace_proto_rawDescOnce sync.Once
	file_pm_v1_workspace_proto_rawDescData []byte
)

func file_pm_v1_workspace_proto_rawDescGZIP() []byte {
	file_pm_v1_workspace_proto_rawDescOnce.Do(func() {
		file_pm_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pm_v1_workspace_proto_rawDesc), len(file_pm_v1_workspace_proto_rawDesc)))
	})
	return file_pm_v1_workspace_proto_rawDescData
}

var file_pm_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pm_v1_workspace_proto_goTypes = []any{
	(*Workspace)(nil),               // 0: pm.v1.Workspace
	(*Project)(nil),                 // 1: pm.v1.Project
	(*Member)(nil),                  // 2: pm.v1.Member
	(*Role)(nil),                    // 3: pm.v1.Role
	(*GetWorkspaceRequest)(nil),     // 4: pm.v1.GetWorkspaceRequest
	(*GetWorkspaceResponse)(nil),    // 5: pm.v1.GetWorkspaceResponse
	(*ListWorkspacesRequest)(nil),   // 6: pm.v1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),  // 7: pm.v1.ListWorkspacesResponse
	(*CheckMembershipRequest)(nil),  // 8: pm.v1.CheckMembershipRequest
	(*CheckMembershipResponse)(nil), // 9: pm.v1.CheckMembershipResponse
	(*WorkspaceCreatedEvent)(nil),   // 10: pm.v1.WorkspaceCreatedEvent
	(*ProjectCreatedEvent)(nil),     // 11: pm.v1.ProjectCreatedEvent
	(*MemberAddedEvent)(nil),        // 12: pm.v1.MemberAddedEvent
	(*MemberRemovedEvent)(nil),      // 13: pm.v1.MemberRemovedEvent
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_pm_v1_workspace_proto_depIdxs = []int32{
	14, // 0: pm.v1.Workspace.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: pm.v1.Member.joined_at:type_name -> google.protobuf.Timestamp
	0,  // 2: pm.v1.GetWorkspaceResponse.workspace:type_name -> pm.v1.Workspace
	0,  // 3: pm.v1.ListWorkspacesResponse.workspaces:type_name -> pm.v1.Workspace
	4,  // 4: pm.v1.WorkspaceService.GetWorkspace:input_type -> pm.v1.GetWorkspaceRequest
	6,  // 5: pm.v1.WorkspaceService.ListWorkspaces:input_type -> pm.v1.ListWorkspacesRequest
	8,  // 6: pm.v1.WorkspaceService.CheckMembership:input_type -> pm.v1.CheckMembershipRequest
	5,  // 7: pm.v1.WorkspaceService.GetWorkspace:output_type -> pm.v1.GetWorkspaceResponse
	7,  // 8: pm.v1.WorkspaceService.ListWorkspaces:output_type -> pm.v1.ListWorkspacesResponse
	9,  // 9: pm.v1.WorkspaceService.CheckMembership:output_type -> pm.v1.CheckMembershipResponse
	7,  // [7:10] is the sub-list for method output_type
	4,  // [4:7] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pm_v1_workspace_proto_init() }
func file_pm_v1_workspace_proto_init() {
	if File_pm_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pm_v1_workspace_proto_rawDesc), len(file_pm_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pm_v1_workspace_proto_goTypes,
		DependencyIndexes: file_pm_v1_workspace_proto_depIdxs,
		MessageInfos:      file_pm_v1_workspace_proto_msgTypes,
	}.Build()
	File_pm_v1_workspace_proto = out.File
	file_pm_v1_workspace_proto_goTypes = nil
	file_pm_v1_workspace_proto_depIdxs = nil
}
